CREATE OR REPLACE VIEW vista_pacientes_consultas AS SELECT p.id_paciente,
    p.origin_id AS originID,
    p.apellido,
    p.nombre,
    p.fecha_nac,
    p.sexo,
    p.edad,
    p.dni,
    p.localidad,
    p.obra_social,
    p.afiliado_nro,
    p.telefono,
    p.telefono_numero,
    p.email,
    p.especialidad,
    p.diagnostico,
    p.enfermedad_base,
    p.ant_perinatales,
    p.ant_familiares,
    p.usuario_registro,
    p.fecha_reg,
    p."createdAt",
    p."updatedAt",
    c.id_consulta,
    c.fecha_consulta,
    c.edad_texto,
    c.peso,
    c.talla,
    c.imc,
    c.pc,
    c.motivo,
    c.conducta,    
    c.origin_id_paciente
   FROM "Pacientes" p
     JOIN "Consultas" c ON p.origin_id = c.origin_id_paciente;